// GENERATED by scripts/analysis/buildArchetypeDecks.js 160 --emit — do not edit.
//
// The deck fitter's table (deckFit.js): a few roster archetypes, each with
// the fifty a two-hundred-game legality profile built for it, and where it
// sits in roster-attribute space. Regenerate after a strategy-card change or
// a default-deck change:
//   node scripts/analysis/buildArchetypeDecks.js 160 --emit
//
// Each archetype's centroid is in the pool's standard deviations on each
// feature (`scale`); deckFit.js measures a roster the same way. The switching
// floors are hard constraints in the builder, so every deck here keeps them.
export const DECK_FIT_SCALE = {
  "speed": {
    "mean": 8.468390804597702,
    "sd": 3.28906770620603
  },
  "power": {
    "mean": 7.85632183908046,
    "sd": 3.4336134630533213
  },
  "threePtBoost": {
    "mean": -0.031609195402298854,
    "sd": 1.871329586680125
  },
  "paintBoost": {
    "mean": -0.028735632183908046,
    "sd": 2.182554026716163
  },
  "defBoost": {
    "mean": 0.011494252873563218,
    "sd": 1.2033884427814021
  }
};

export const ARCHETYPE_DECKS = [
  {
    "id": "fast",
    "centroid": {
      "speed": 0.7088966855266813,
      "power": -1.03573738784156,
      "threePtBoost": 0.6047086539201553,
      "paintBoost": -0.4450127492502173,
      "defBoost": -0.5912423849019859
    },
    "deck": {
      "power_move": 1,
      "and_one": 1,
      "cold_spell": 1,
      "bully_ball": 2,
      "from_way_downtown": 1,
      "heat_check": 1,
      "drive_the_lane": 1,
      "catch_and_shoot": 2,
      "green_light": 1,
      "you_stand_over_there": 1,
      "pick_up_full_court": 1,
      "turnover": 1,
      "elevator_doors": 1,
      "crowd_favorite": 1,
      "offensive_board": 1,
      "cross_court_dime": 1,
      "anticipate_pass": 1,
      "rebound_tap_out": 1,
      "high_screen_roll": 4,
      "double_team": 1,
      "this_is_my_house": 1,
      "uncontested_layup": 1,
      "close_out": 1,
      "stagger_action": 1,
      "coaches_challenge": 1,
      "offensive_foul": 1,
      "switch_everything": 2,
      "second_closer": 1,
      "go_under": 2,
      "veer_switch": 3,
      "ato_masterpiece": 1,
      "fight_over": 2,
      "desperation_press": 1,
      "overhelp": 2,
      "burned_switch": 2,
      "ice_the_hot_hand": 1,
      "reset": 1,
      "fresh_legs": 1
    }
  },
  {
    "id": "big",
    "centroid": {
      "speed": -0.41604215140227485,
      "power": 0.4787021540444185,
      "threePtBoost": -0.6778019295082696,
      "paintBoost": 0.7920700294347063,
      "defBoost": 0.23974448886978753
    },
    "deck": {
      "power_move": 1,
      "and_one": 1,
      "cold_spell": 1,
      "bully_ball": 1,
      "from_way_downtown": 1,
      "heat_check": 1,
      "drive_the_lane": 1,
      "catch_and_shoot": 1,
      "green_light": 1,
      "you_stand_over_there": 1,
      "pick_up_full_court": 1,
      "turnover": 1,
      "elevator_doors": 1,
      "crowd_favorite": 1,
      "offensive_board": 1,
      "cross_court_dime": 1,
      "anticipate_pass": 1,
      "rebound_tap_out": 1,
      "high_screen_roll": 4,
      "double_team": 1,
      "this_is_my_house": 1,
      "uncontested_layup": 1,
      "close_out": 1,
      "stagger_action": 1,
      "coaches_challenge": 1,
      "putback_dunk": 1,
      "rimshaker": 1,
      "offensive_foul": 1,
      "back_to_basket": 1,
      "switch_everything": 1,
      "second_closer": 1,
      "go_under": 2,
      "veer_switch": 3,
      "ato_masterpiece": 1,
      "fight_over": 2,
      "desperation_press": 1,
      "overhelp": 2,
      "burned_switch": 2,
      "ice_the_hot_hand": 1,
      "reset": 1,
      "fresh_legs": 1
    }
  },
  {
    "id": "stoppy",
    "centroid": {
      "speed": 0.07041788618862485,
      "power": 0.18746378060480726,
      "threePtBoost": 0.12376718513449597,
      "paintBoost": 0.10480181905419318,
      "defBoost": 0.9045339878872063
    },
    "deck": {
      "power_move": 1,
      "and_one": 1,
      "cold_spell": 1,
      "bully_ball": 1,
      "from_way_downtown": 1,
      "drive_the_lane": 1,
      "catch_and_shoot": 2,
      "green_light": 1,
      "you_stand_over_there": 1,
      "pick_up_full_court": 1,
      "turnover": 1,
      "elevator_doors": 1,
      "crowd_favorite": 1,
      "offensive_board": 1,
      "cross_court_dime": 1,
      "anticipate_pass": 1,
      "rebound_tap_out": 1,
      "high_screen_roll": 4,
      "double_team": 1,
      "this_is_my_house": 1,
      "uncontested_layup": 1,
      "close_out": 1,
      "stagger_action": 1,
      "coaches_challenge": 1,
      "putback_dunk": 1,
      "rimshaker": 1,
      "offensive_foul": 1,
      "back_to_basket": 1,
      "switch_everything": 1,
      "second_closer": 1,
      "go_under": 2,
      "veer_switch": 3,
      "ato_masterpiece": 1,
      "fight_over": 2,
      "desperation_press": 1,
      "overhelp": 2,
      "burned_switch": 2,
      "ice_the_hot_hand": 1,
      "reset": 1,
      "fresh_legs": 1
    }
  }
];
