// GENERATED by scripts/analysis/runStratAudit.js --emit-deck - do not edit.
//
// The default 50-card deck, learned from 600 seeded AI-vs-AI games:
// every card keeps at least one copy, the SWITCHING FAMILY keeps its design
// floor (High Screen & Roll 4, Veer Switch 3, Burned on the Switch 3, Go Under,
// Fight Over, Overhelp 2 - the user's steer), proven win rates earn extras
// under the 5/3/1 copy caps, and the fill goes to the most-played staples.
// Regenerate after AI or card changes:
//   dropped to fit fifty (fewest AI plays first): burst_of_momentum, dogged, second_wind, delayed_slip, ghost_screen, chip_on_shoulder, energy_injection, flare_screen, defensive_stopper, pin_down_screen
//   node scripts/analysis/runStratAudit.js 600 --full --emit-deck
// HAND EDIT 2026-09-16 (the user: "go for it"). The emitter can no longer
// reach fifty: its protected classes - floors, crunch riders, reactions,
// proven cards, design keeps - are 53 cards on their own. So, by its own
// last-resort rule (fewest AI plays first, never a protected card):
//   + burst_of_momentum  reworked, its door could never open before; lift +25 in the 600-game audit
//   + post_domination    reworked to a matchup door; lift +38
//   - cross_court_dime   17 plays, 35% when played, lift -19
//   - turnover           49% when played, lift -21 (the rule's literal pick was Stagger Action, a play-based card the steer keeps)
export const DEFAULT_DECK_COPIES = {
  "power_move": 1,
  "and_one": 1,
  "cold_spell": 1,
  "bully_ball": 1,
  "from_way_downtown": 1,
  "heat_check": 1,
  "drive_the_lane": 1,
  "catch_and_shoot": 1,
  "green_light": 1,
  "you_stand_over_there": 1,
  "pick_up_full_court": 1,
  "burst_of_momentum": 1,
  "elevator_doors": 1,
  "crowd_favorite": 1,
  "offensive_board": 1,
  "post_domination": 1,
  "anticipate_pass": 1,
  "rebound_tap_out": 1,
  "high_screen_roll": 4,
  "double_team": 1,
  "this_is_my_house": 1,
  "uncontested_layup": 1,
  "close_out": 1,
  "stagger_action": 1,
  "coaches_challenge": 1,
  "putback_dunk": 1,
  "rimshaker": 1,
  "offensive_foul": 1,
  "back_to_basket": 1,
  "switch_everything": 1,
  "second_closer": 1,
  "go_under": 2,
  "veer_switch": 3,
  "ato_masterpiece": 1,
  "fight_over": 2,
  "desperation_press": 1,
  "overhelp": 2,
  "burned_switch": 2,
  "ice_the_hot_hand": 1,
  "reset": 1,
  "fresh_legs": 1
};
