// The sound of opening a pack — SYNTHESIZED, not sampled.
//
// ── WHY THERE ARE NO .MP3 FILES HERE ────────────────────────────────────────
//
// Every sound in this file is generated by the Web Audio API at play time. The
// alternative was shipping five or six audio files, and that costs three things
// this buys back for free: bytes in the bundle, a licence for each clip, and a
// network round trip at the exact moment the player is waiting for a card. It
// also means the escalation is a NUMBER rather than a recording — a legendary
// chime is the rare chime with more partials and a longer tail, so tuning the
// ladder is editing one table instead of re-cutting six files.
//
// The one existing sample stays: `lebron.mp3` is a joke, and a joke cannot be
// synthesized. See PackOpening.
//
// ── AUTOPLAY, AND WHY NOTHING HAPPENS UNTIL A CLICK ─────────────────────────
//
// Browsers refuse to start an AudioContext that no gesture asked for, and a
// refused context does not throw — it sits in `suspended` and plays silence.
// So the context is created LAZILY on the first sound, which by construction
// happens inside a click handler (the player tapped a card), and `resume()` is
// called every time in case the tab was backgrounded. A browser that still says
// no gets silence and no errors; sound is a garnish and must never be able to
// break a pack open.
//
// ── THE MUTE IS THE PLAYER'S, AND IT PERSISTS ───────────────────────────────
//
// Stored in localStorage, read once at module load, and defaulting to ON. A
// muted session that forgets itself is worse than no sound at all, and reading
// storage can throw outright in a private window, so every access is guarded.

const STORAGE_KEY = 'showdown-sound';

let ctx = null;
let muted = false;
try {
  muted = localStorage.getItem(STORAGE_KEY) === 'off';
} catch {
  muted = false;
}

export function isMuted() {
  return muted;
}

/** Flip the mute and persist it. Returns the new muted state. */
export function toggleMute() {
  muted = !muted;
  try {
    localStorage.setItem(STORAGE_KEY, muted ? 'off' : 'on');
  } catch {
    // A browser that refuses storage still gets the toggle for this session.
  }
  return muted;
}

/**
 * The shared AudioContext, created on first use inside a gesture.
 *
 * Returns null when audio is unavailable — an old browser, a locked-down one,
 * or a context the browser refused to build. Every caller treats null as
 * "no sound" rather than as an error.
 */
function audio() {
  if (muted) return null;
  try {
    if (!ctx) {
      const Ctor = window.AudioContext || window.webkitAudioContext;
      if (!Ctor) return null;
      ctx = new Ctor();
    }
    // A context can be suspended by the browser at any time (tab hidden, policy
    // change). Resuming an already-running context is a no-op.
    if (ctx.state === 'suspended') ctx.resume().catch(() => {});
    return ctx;
  } catch {
    return null;
  }
}

/**
 * One note.
 *
 * `type` is the oscillator shape, and it is what makes the ladder audible: a
 * sine is soft and flute-like, a triangle has more edge, a sawtooth is bright
 * and brassy. The rarer the card, the brighter the wave.
 */
function tone(ac, {
  freq, start = 0, dur = 0.3, gain = 0.12, type = 'sine', glide = 0,
  // The instrument's three knobs — see INSTRUMENTS. All optional; the defaults
  // reproduce the original chime exactly.
  overtone = null,   // { ratio, gain }: a second partial, e.g. a bell's inharmonic 2.76x
  detune = 0,        // cents on a second oscillator, for the Dissonance shimmer
  lowpass = null,    // { from, to }: a filter sweep, which is what makes a pluck
}) {
  const t0 = ac.currentTime + start;
  const amp = ac.createGain();
  let out = amp;
  if (lowpass) {
    const filter = ac.createBiquadFilter();
    filter.type = 'lowpass';
    filter.frequency.setValueAtTime(lowpass.from, t0);
    filter.frequency.exponentialRampToValueAtTime(Math.max(40, lowpass.to), t0 + dur);
    amp.connect(filter).connect(ac.destination);
  } else {
    amp.connect(ac.destination);
  }

  const voice = (f, g, cents = 0) => {
    const osc = ac.createOscillator();
    osc.type = type;
    osc.frequency.setValueAtTime(f, t0);
    if (cents) osc.detune.setValueAtTime(cents, t0);
    // A glide is what turns two notes into one gesture — used for the whoosh.
    if (glide) osc.frequency.exponentialRampToValueAtTime(Math.max(1, glide), t0 + dur);
    const vg = ac.createGain();
    vg.gain.setValueAtTime(g, t0);
    osc.connect(vg).connect(out);
    osc.start(t0);
    osc.stop(t0 + dur + 0.05);
  };

  // Attack fast, decay slow. setValueAtTime(0) first: an exponential ramp from
  // exactly zero is undefined and silently produces nothing in some engines.
  amp.gain.setValueAtTime(0.0001, t0);
  amp.gain.exponentialRampToValueAtTime(gain, t0 + Math.min(0.02, dur / 4));
  amp.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  voice(freq, 1);
  if (detune) voice(freq, 0.7, detune);
  if (overtone) voice(freq * overtone.ratio, overtone.gain);
}

/** Filtered white noise — the air in a whoosh, and the fizz under a burst. */
function noise(ac, { start = 0, dur = 0.25, gain = 0.06, from = 900, to = 200 }) {
  const t0 = ac.currentTime + start;
  const frames = Math.max(1, Math.floor(ac.sampleRate * dur));
  const buffer = ac.createBuffer(1, frames, ac.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i += 1) data[i] = Math.random() * 2 - 1;

  const src = ac.createBufferSource();
  src.buffer = buffer;
  const filter = ac.createBiquadFilter();
  filter.type = 'bandpass';
  filter.frequency.setValueAtTime(from, t0);
  filter.frequency.exponentialRampToValueAtTime(Math.max(1, to), t0 + dur);
  const amp = ac.createGain();
  amp.gain.setValueAtTime(gain, t0);
  amp.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  src.connect(filter).connect(amp).connect(ac.destination);
  src.start(t0);
  src.stop(t0 + dur + 0.05);
}

/**
 * THE LADDER. One row per rarity, and the whole escalation lives here.
 *
 * `notes` is a chord spelled in semitones above the root, played as a fast
 * arpeggio. The rows are chosen so the interval itself carries the news before
 * any effect on screen does:
 *
 *   common      a bare fifth, over almost as soon as it starts
 *   uncommon    a major triad — pleasant, unremarkable
 *   rare        a major sixth chord, brighter wave, longer tail
 *   super-rare  a major seventh climbing an octave, sawtooth
 *   legendary   a full stacked major ninth, two octaves, with a sub beneath it
 *
 * `root` rises with rarity too, so the rarer card is literally higher pitched.
 */
const CHIMES = {
  common: { root: 392, notes: [0, 7], dur: 0.18, type: 'sine', gain: 0.07 },
  uncommon: { root: 440, notes: [0, 4, 7], dur: 0.26, type: 'sine', gain: 0.08 },
  rare: { root: 523, notes: [0, 4, 7, 9], dur: 0.42, type: 'triangle', gain: 0.09 },
  'super-rare': { root: 587, notes: [0, 4, 7, 11, 12], dur: 0.62, type: 'sawtooth', gain: 0.075 },
  legendary: {
    root: 659,
    notes: [0, 4, 7, 11, 14, 16, 19, 24],
    dur: 0.95,
    type: 'sawtooth',
    gain: 0.07,
    sub: true,
  },
};

const semitone = (root, n) => root * 2 ** (n / 12);

/**
 * THE INSTRUMENTS. One per kind of set; the rarity ladder plays THROUGH them.
 *
 * The ladder above says how big the news is. This table says what the news
 * sounds like, so a gold pull and a rookie pull of the same rarity are not
 * the same chime. Each entry bends the ladder's row rather than replacing it:
 * a shift of the root, a stretch of the tail, a partial or two, a filter —
 * and the ladder's own escalation (higher, longer, brighter as rarity climbs)
 * still holds inside every instrument.
 *
 *   base            the original chime, untouched
 *   super-season    a BELL — the 2.76x partial every real bell has, longer tail
 *   rookie          a PULSE — square wave, quick decay, a fourth higher: bouncy
 *   summer-standouts a PLUCK — sawtooth under a closing lowpass, short
 *   dissonance      the tritone added to every chord, and a detuned twin — the
 *                   wrong jersey, audibly
 *   team-rewards    a FANFARE — a pickup note a fourth below, then the chord
 *   strats          a soft pluck, quiet; a strategy card is not the headline
 *
 * The WNBA is not a kind but a VOICING: any of the above, a minor third up and
 * with an octave shimmer, applied on top of the set kind. So a WNBA rookie is
 * the rookie pulse, brighter, and a WNBA reward is the fanfare, brighter.
 */
export const INSTRUMENTS = {
  base: { shift: 0, tail: 1 },
  'super-season': { shift: 0, tail: 1.5, type: 'sine', overtone: { ratio: 2.76, gain: 0.35 } },
  rookie: { shift: 5, tail: 0.7, type: 'square', gain: 0.6, spread: 0.6 },
  'summer-standouts': { shift: 2, tail: 0.8, type: 'sawtooth', lowpass: { from: 3200, to: 380 }, gain: 0.9 },
  dissonance: { shift: -2, tail: 1.1, type: 'sawtooth', extraNotes: [6], detune: 9, gain: 0.8 },
  'team-rewards': { shift: 0, tail: 1.3, pickup: -5, gain: 0.95 },
  strats: { shift: -7, tail: 0.6, type: 'triangle', lowpass: { from: 2400, to: 500 }, gain: 0.55 },
};

const WNBA_VOICING = { shift: 3, overtone: { ratio: 2, gain: 0.3 } };

/** The instrument a set plays through. Unknown sets get the base chime. */
export function instrumentFor(set) {
  const id = String(set ?? '');
  const wnba = id === 'wnba' || id.startsWith('wnba-');
  const kind = wnba ? id.replace(/^wnba-?/, '') || 'base' : id;
  const base = INSTRUMENTS[kind] ?? INSTRUMENTS.base;
  if (!wnba) return base;
  return {
    ...base,
    shift: (base.shift ?? 0) + WNBA_VOICING.shift,
    // A kind with a partial of its own keeps it; the shimmer is for the rest.
    overtone: base.overtone ?? WNBA_VOICING.overtone,
    wnba: true,
  };
}

/** The card turning over. Same for every rarity — the news comes after. */
export function playFlip() {
  const ac = audio();
  if (!ac) return;
  noise(ac, { dur: 0.22, gain: 0.05, from: 1800, to: 300 });
}

/**
 * The reveal, escalating by rarity.
 *
 * Notes are spread across the chime's duration rather than struck together, so
 * a legendary does not arrive as a single crunch — it unfurls, which is most of
 * why it reads as bigger than a rare rather than just louder.
 */
export function playReveal(rarity, set = null) {
  const ac = audio();
  if (!ac) return;
  const chime = CHIMES[rarity] ?? CHIMES.common;
  const inst = instrumentFor(set);
  const dur = chime.dur * (inst.tail ?? 1);
  const gain = chime.gain * (inst.gain ?? 1);
  const type = inst.type ?? chime.type;
  const root = semitone(chime.root, inst.shift ?? 0);
  const spread = dur * 0.35 * (inst.spread ?? 1);
  const notes = inst.extraNotes ? [...chime.notes, ...inst.extraNotes] : chime.notes;

  // The fanfare's pickup: one short note below the root, before the chord.
  let lead = 0;
  if (inst.pickup) {
    tone(ac, { freq: semitone(root, inst.pickup), dur: dur * 0.35, gain: gain * 0.9, type });
    lead = dur * 0.22;
  }

  notes.forEach((n, i) => {
    tone(ac, {
      freq: semitone(root, n),
      start: lead + (i / Math.max(1, notes.length - 1)) * spread,
      dur,
      gain,
      type,
      overtone: inst.overtone ?? null,
      detune: inst.detune ?? 0,
      lowpass: inst.lowpass ?? null,
    });
  });

  // The legendary alone gets a sub-bass thump and a shimmer of noise on top —
  // the two things a chime cannot do, held back so they mean something.
  if (chime.sub) {
    tone(ac, { freq: 55, dur: 1.1, gain: 0.16, type: 'sine' });
    noise(ac, { start: 0.05, dur: 0.9, gain: 0.03, from: 5000, to: 2200 });
  }
}

/** Every card seen. A short rising two-note figure, deliberately modest. */
export function playComplete() {
  const ac = audio();
  if (!ac) return;
  tone(ac, { freq: 523, dur: 0.18, gain: 0.07, type: 'triangle' });
  tone(ac, { freq: 784, start: 0.11, dur: 0.3, gain: 0.07, type: 'triangle' });
}

/** Exported for tests: the tiers that have a declared chime. */
export const CHIME_RARITIES = Object.keys(CHIMES);
export { CHIMES };
