// NBA Showdown 2K25 — Strategy card definitions
export const STRATS = [
  // ── MATCHUP PHASE ──
  { id:'high_screen_roll',    name:'High Screen & Roll', phase:'matchup',  side:'off', copies:2, locked:false, color:'#0369A1',
    desc:'Select two of your own players to swap their defenders. The opponent may react with Go Under, Fight Over, or Veer Switch.' },
  { id:'stagger_action',      name:'Stagger Action',     phase:'matchup',  side:'off', copies:2, locked:false, color:'#0284C7',
    desc:'One player with Speed 13+ and one with a 3PT Bonus each gain +2 Speed for this segment.' },
  { id:'second_wind',         name:'Second Wind',        phase:'matchup',  side:'off', copies:2, locked:false, color:'#16A34A',
    desc:'Choose a fatigued player. They ignore their fatigue penalty this segment (gains +1 fatigue marker after).' },
  { id:'chip_on_shoulder',    name:'Chip on the Shoulder', phase:'matchup', side:'off', copies:2, locked:false, color:'#D97706',
    desc:'Player with salary ≤$250 gets +2 Speed and +2 Power this segment. If they now have a positive roll bonus, draw a card.' },
  { id:'defensive_stopper',   name:'Defensive Stopper',  phase:'matchup',  side:'def', copies:2, locked:false, color:'#1D4ED8',
    desc:'Choose a player who was benched last segment. They gain +5 Speed and +5 Power on defense this segment.' },

  // ── PRE-ROLL ──
  { id:'ghost_screen',        name:'Ghost Screen',       phase:'pre_roll', side:'off', copies:2, locked:false, color:'#6366F1',
    desc:'Choose an offensive player with Speed 12+. They are treated as having no defender for matchup advantage — roll penalty is negated to 0.' },
  { id:'you_stand_over_there',name:'You Stand Over There',phase:'pre_roll',side:'off', copies:2, locked:false, color:'#7C3AED',
    desc:'Before a player makes their scoring roll: they skip it and attempt two 3PT Shot Checks instead.' },
  { id:'putback_dunk',        name:'Putback Dunk',       phase:'pre_roll', side:'off', copies:2, locked:false, color:'#7C3AED',
    desc:'Your team leads in rebounds and a player has Power 14+: score 2 points automatically.' },
  { id:'pin_down_screen',     name:'Pin-Down Screen',    phase:'pre_roll', side:'off', copies:2, locked:false, color:'#BE185D',
    desc:'Discard a card. Choose a player to attempt a 3PT Shot Check at +5. Success: 3 pts + 1 assist to a teammate.' },
  { id:'turnover',            name:'Turnover',           phase:'pre_roll', side:'def', copies:2, locked:false, color:'#DC2626',
    desc:'Opponent has a cold marker: draw 2 strategy cards.' },

  // ── SCORING PHASE ──
  { id:'green_light',         name:'Green Light',        phase:'scoring',  side:'off', copies:2, locked:false, color:'#16A34A',
    desc:'Select one player to attempt three 3PT Shot Checks instead of their scoring roll.' },
  { id:'from_way_downtown',   name:'From Way Downtown',  phase:'scoring',  side:'off', copies:3, locked:false, color:'#2563EB',
    desc:'3PT Shot Check at +1. Roll 1–3: cold marker. Roll 18–20: hot marker.' },
  { id:'catch_and_shoot',     name:'Catch & Shoot',      phase:'scoring',  side:'off', copies:3, locked:false, color:'#0891B2',
    desc:'Player with Speed 12+ attempts a 3PT Shot Check at +2. Success: +1 assist.' },
  { id:'elevator_doors',      name:'Elevator Doors',     phase:'scoring',  side:'off', copies:2, locked:false, color:'#EA580C',
    desc:'Choose a player with a 3PT Bonus. They attempt a 3PT Shot Check at an additional +3.' },
  { id:'bully_ball',          name:'Bully Ball',         phase:'scoring',  side:'off', copies:3, locked:false, color:'#DC2626',
    desc:'Player with a Power advantage attempts two Paint Shot Checks. Power advantage ≥4: +2 to each check.' },
  { id:'power_move',          name:'Power Move',         phase:'scoring',  side:'off', copies:3, locked:false, color:'#9333EA',
    desc:'Choose a player: +2 Power. If their Power advantage is already ≥5: +3 Power instead.' },
  { id:'and_one',             name:'And One!!!',         phase:'scoring',  side:'off', copies:3, locked:true,  color:'#F59E0B',
    desc:'Speed or Power advantage ≥3: +1 pt. Advantage ≥5: also attempt a free throw check. 🔒 Uncancelable.' },
  { id:'rimshaker',           name:'Rimshaker',          phase:'scoring',  side:'off', copies:2, locked:false, color:'#EF4444',
    desc:'Player has Power 13+ and a hot marker: +2 pts and add another hot marker.' },
  { id:'drive_the_lane',      name:'Drive the Lane',     phase:'scoring',  side:'off', copies:3, locked:false, color:'#0EA5E9',
    desc:'Player with a Speed advantage attempts two free throw checks. Speed advantage ≥5: defender gains a cold marker.' },
  { id:'uncontested_layup',   name:'Uncontested Layup',  phase:'scoring',  side:'off', copies:2, locked:false, color:'#10B981',
    desc:'Any of your players with +2 Speed AND +2 Power advantage over their matchup automatically scores 2 pts.' },
  { id:'back_to_basket',      name:'Back to the Basket', phase:'scoring',  side:'off', copies:2, locked:false, color:'#B45309',
    desc:'Player with Power 13+ and a Paint Bonus attempts a Paint Shot Check.' },
  { id:'cross_court_dime',    name:'Cross-Court Dime',   phase:'scoring',  side:'off', copies:2, locked:false, color:'#7C3AED',
    desc:'Spend 3 assists: player skips scoring roll and makes one Paint + one 3PT Shot Check instead.' },
  { id:'energy_injection',    name:'Energy Injection',   phase:'scoring',  side:'off', copies:2, locked:false, color:'#059669',
    desc:'Two players with salary <$400 each get +1 to their scoring roll. If either scores 4+: +1 assist.' },
  { id:'crowd_favorite',      name:'Crowd Favorite',     phase:'scoring',  side:'off', copies:2, locked:false, color:'#F97316',
    desc:'Player with salary ≤$350: if they score 5+ pts this segment, they gain a hot marker.' },
  { id:'switch_everything',   name:'Switch Everything',  phase:'scoring',  side:'def', copies:2, locked:true,  color:'#1D4ED8',
    desc:'Fully reassign your defense: choose who guards each of the opponent\'s players. All opponent offensive advantages are doubled. 🔒 Uncancelable.' },
  { id:'this_is_my_house',    name:'This Is My House!',  phase:'scoring',  side:'def', copies:2, locked:true,  color:'#991B1B',
    desc:'Your defender has higher Speed AND Power than their offensive matchup: that player skips their scoring roll entirely. 🔒 Uncancelable.' },

  // ── POST-ROLL ──
  { id:'heat_check',          name:'Heat Check',         phase:'post_roll',side:'off', copies:3, locked:true,  color:'#F97316',
    desc:'A player hit their highest scoring tier: attempt a 3PT Shot Check at −2. Success: +3 pts + hot marker. 🔒 Uncancelable.' },
  { id:'burst_of_momentum',   name:'Burst of Momentum',  phase:'post_roll',side:'off', copies:2, locked:false, color:'#DC2626',
    desc:'Player hits their top tier AND scores 5+ pts this segment: +1 AST, +1 REB, and a hot marker.' },
  { id:'flare_screen',        name:'Flare Screen',       phase:'post_roll',side:'off', copies:2, locked:false, color:'#F59E0B',
    desc:'A player rolled a natural 20: they make a 3PT Shot Check. Success: +3 pts + draw a card.' },

  // ── REACTION ──
  { id:'go_under',            name:'Go Under',           phase:'reaction', side:'def', copies:2, locked:false, color:'#6D28D9',
    desc:'Cancel opponent\'s screen-and-roll card. The offensive player involved gets a 3PT Shot Check at +2.' },
  { id:'fight_over',          name:'Fight Over',         phase:'reaction', side:'def', copies:2, locked:false, color:'#B45309',
    desc:'Cancel opponent\'s screen-and-roll card. The faster of the two involved offensive players gets +2 to their scoring roll.' },
  { id:'veer_switch',         name:'Veer Switch',        phase:'reaction', side:'def', copies:2, locked:false, color:'#7C3AED',
    desc:'Cancel opponent\'s screen-and-roll card. You choose the new defender assignments instead.' },
  { id:'close_out',           name:'Close Out',          phase:'reaction', side:'def', copies:3, locked:false, color:'#15803D',
    desc:'When opponent announces a 3PT Shot Check: −3 to that check. If they miss: cold marker on that player.' },
  { id:'cold_spell',          name:'Cold Spell',         phase:'reaction', side:'def', copies:3, locked:false, color:'#0284C7',
    desc:'Opponent rolls a natural 1 or 2 on their scoring roll: apply a cold marker + reduce their Rebound Track by 1.' },
  { id:'anticipate_pass',     name:'Anticipate the Pass',phase:'reaction', side:'def', copies:2, locked:false, color:'#0F766E',
    desc:'Opponent has 6+ assists: spend 1 of your assists to remove 2 from their track.' },
  { id:'offensive_foul',      name:'Offensive Foul',     phase:'reaction', side:'def', copies:2, locked:false, color:'#64748B',
    desc:'Play after an opponent activates a card that boosts Power. Their Power boost is halved (rounded down), and they suffer −1 Rebound.' },
  { id:'dogged',              name:'Dogged',             phase:'scoring',  side:'def', copies:2, locked:false, color:'#78716C',
    desc:'Target an opposing fatigued player: they suffer an additional −2 Speed and −2 Power until benched for a segment.' },
  { id:'overhelp',            name:'Overhelp',           phase:'reaction', side:'off', copies:2, locked:false, color:'#0369A1',
    desc:'Opponent plays a defensive switching card: one of your players gets +2 to their scoring roll this segment.' },
  { id:'burned_switch',       name:'Burned on the Switch',phase:'reaction',side:'off', copies:2, locked:false, color:'#DC2626',
    desc:'Opponent forces a matchup switch: if the new defender has lower Speed OR Power than the original, you get +3 to your scoring roll.' },
  { id:'offensive_board',     name:'Offensive Board Mastery',phase:'reaction',side:'off',copies:2,locked:false,color:'#EA580C',
    desc:'Spend 3 rebounds: take a second scoring roll with a different player at −2.' },
  { id:'rebound_tap_out',     name:'Rebound Tap-Out',    phase:'reaction', side:'off', copies:2, locked:false, color:'#F59E0B',
    desc:'Spend 2 rebounds: +1 assist to a player with a 3PT Bonus. That player makes a 3PT Shot Check at +1.' },

  // ── SPECIAL ──
  { id:'coaches_challenge',   name:"Coach's Challenge",  phase:'reaction', side:'def', copies:2, locked:false, color:'#B91C1C',
    desc:'Challenge the last play. Re-roll the opponent\'s most recent scoring roll. They must accept the new result.' },
  { id:'delayed_slip',        name:'Delayed Slip',       phase:'scoring',  side:'off', copies:2, locked:false, color:'#7C3AED',
    desc:'Choose a player with Speed ≥12 and Power ≥10. If they have no matchup advantage, give them +2 to scoring roll and +1 Rebound.' },
];

export const STRAT_MAP = Object.fromEntries(STRATS.map(s => [s.id, s]));

export function getStrat(id) {
  return STRAT_MAP[id];
}
