import { describe, it, expect } from 'vitest';
import {
  playerIdFromName,
  POOL_PLAYERS,
  CARD_PLAYERS,
  SOURCES,
  photoProgress,
  filterPlayers,
  stepSelection,
  TEAMS_RESOLVED,
} from './players.js';
import { isSafePlayerId } from '../../scripts/studio/studioServerPlugin.js';
import { getTeam } from '../cards/teams.js';

const P = (id, name, team, pos) => ({ id, name, team, pos });

const SAMPLE = [
  P('Tyrese_Maxey', 'Tyrese Maxey', 'PHI', 'PG'),
  P('Kevin_Durant', 'Kevin Durant', 'HOU', 'SF'),
  P('Luka_Doncic', 'Luka Dončić', 'LAL', 'PG'),
];

describe('playerIdFromName', () => {
  it('joins name parts with underscores', () => {
    expect(playerIdFromName('Kevin Durant')).toBe('Kevin_Durant');
  });

  it('collapses runs of punctuation into a single underscore', () => {
    expect(playerIdFromName("De'Aaron Fox")).toBe('De_Aaron_Fox');
    expect(playerIdFromName('A.J. Green')).toBe('A_J_Green');
  });

  it('trims the underscore a trailing suffix dot would leave', () => {
    // "Jabari_Smith_Jr_" would be the id; the shipped set spells it
    // "Jabari_Smith_Jr", and this id is a filename people read.
    expect(playerIdFromName('Jabari Smith Jr.')).toBe('Jabari_Smith_Jr');
    expect(playerIdFromName('  Kevin Durant  ')).toBe('Kevin_Durant');
  });

  it('strips diacritics instead of collapsing them to underscores', () => {
    // This id is the photo filename, so the scheme must not churn — and the
    // form it is pinned to is the one the repo already ships: card art named
    // "Vit_Krejci.png", ids in src/game/rawCards.js like "Alperen_Sengun".
    expect(playerIdFromName('Luka Dončić')).toBe('Luka_Doncic');
    expect(playerIdFromName('Nikola Jokić')).toBe('Nikola_Jokic');
    expect(playerIdFromName('Alperen Şengün')).toBe('Alperen_Sengun');
    expect(playerIdFromName('Vít Krejčí')).toBe('Vit_Krejci');
    expect(playerIdFromName('Jonas Valančiūnas')).toBe('Jonas_Valanciunas');
    expect(playerIdFromName('Dennis Schröder')).toBe('Dennis_Schroder');
  });

  it('keeps case and word breaks, unlike a cross-source match key', () => {
    // resolveTeams.js's normalizeName lowercases and drops separators to match
    // names across feeds. This is a filename, so it must stay readable.
    expect(playerIdFromName('Luka Dončić')).not.toBe('lukadoncic');
  });

  it('survives a missing name instead of throwing', () => {
    expect(playerIdFromName(undefined)).toBe('');
    expect(playerIdFromName(null)).toBe('');
    expect(playerIdFromName('...')).toBe('');
  });
});

describe('the 2025-26 pool', () => {
  it('loads all 331 players', () => {
    expect(POOL_PLAYERS).toHaveLength(331);
  });

  it('gives every player a unique id', () => {
    const ids = new Set(POOL_PLAYERS.map(p => p.id));
    expect(ids.size).toBe(POOL_PLAYERS.length);
  });

  it('produces ids the studio server will accept as filenames', () => {
    // The upload route rejects any id outside [A-Za-z0-9_.-]; an id it refuses
    // is a player whose photo can never be saved.
    const rejected = POOL_PLAYERS.filter(p => !isSafePlayerId(p.id)).map(p => p.name);
    expect(rejected).toEqual([]);
  });

  it('carries name, team and position and no generated stats', () => {
    const maxey = POOL_PLAYERS.find(p => p.name === 'Tyrese Maxey');
    expect(maxey).toMatchObject({ id: 'Tyrese_Maxey', team: 'PHI', pos: 'PG' });
    expect(maxey.chart).toBeUndefined();
    expect(maxey.salary).toBeUndefined();
  });

  it('leaves no underscore where a diacritic used to be', () => {
    // A letter this scheme cannot decompose (Đ, ø, ł — none of which NFD
    // touches) would silently become an underscore again. Doubled or edge
    // underscores are the symptom, so fail on them by name.
    const ugly = POOL_PLAYERS.filter(p => /^_|_$|__/.test(p.id)).map(p => p.name);
    expect(ugly).toEqual([]);
  });
});

describe('resolved teams overlaid on the pool', () => {
  // These assert the file generated by scripts/cardgen/generateTeams.js is
  // actually reaching the studio. Without it, 45 players render on the grey
  // "Unknown" theme with no logo — the single most visible thing wrong with the
  // set — and no pool player can fall back to an NBA headshot.
  const MULTI_TEAM = /^(2TM|3TM|4TM|TOT)$/;

  it('is switched on in this checkout', () => {
    expect(TEAMS_RESOLVED).toBe(true);
  });

  it('replaces the multi-team aggregate codes with real teams', () => {
    const stuck = POOL_PLAYERS.filter(p => MULTI_TEAM.test(p.team)).map(p => p.name);
    // Only the players no source can place: on no active roster AND carrying an
    // aggregate code. They stay in the list and stay visibly unthemed, which is
    // the point — they need a human decision, recorded in manual-teams.json.
    expect(stuck).toEqual([
      'Cam Thomas',
      'Vince Williams Jr.',
      'Ochai Agbaji',
      'Guerschon Yabusele',
    ]);
  });

  it('keeps every pool player, including the ones it could not resolve', () => {
    // The resolved file is SHORTER than the pool (327 vs 331). Reading it as the
    // list rather than as an overlay would silently drop 4 players from the set.
    expect(POOL_PLAYERS).toHaveLength(331);
  });

  it('gives resolved players the personId the headshot fallback needs', () => {
    const harden = POOL_PLAYERS.find(p => p.name === 'James Harden');
    // Traded mid-season: "2TM" in the raw pool, a real team here.
    expect(harden).toMatchObject({ team: 'CLE', personId: 201935 });
    const withId = POOL_PLAYERS.filter(p => p.personId).length;
    expect(withId).toBeGreaterThan(300);
  });

  it('leaves the unresolvable few with an explicit null personId', () => {
    const thomas = POOL_PLAYERS.find(p => p.name === 'Cam Thomas');
    expect(thomas.personId).toBeNull();
  });

  it('names every team in a form the card theming knows', () => {
    // A team abbreviation getTeam() cannot find renders grey with no logo. The
    // four unresolved players are the only ones allowed to look like that.
    const unthemed = POOL_PLAYERS.filter(p => getTeam(p.team).name === 'Unknown').map(p => p.name);
    expect(unthemed).toHaveLength(4);
  });
});

describe('photo-id collisions', () => {
  // The photo directory is ONE namespace shared by both sources, so this is the
  // check that matters: two different people must never derive the same
  // filename, or curating one silently overwrites the other's photo.
  const bare = name =>
    name
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '');

  it('gives all 331 pool players distinct ids', () => {
    expect(new Set(POOL_PLAYERS.map(p => p.id)).size).toBe(331);
  });

  it('gives all 306 shipped cards distinct ids', () => {
    expect(new Set(CARD_PLAYERS.map(p => p.id)).size).toBe(306);
  });

  it('never gives two different people the same id across both sets', () => {
    const byId = new Map();
    const clashes = [];
    for (const p of [...POOL_PLAYERS, ...CARD_PLAYERS]) {
      const seen = byId.get(p.id);
      if (seen === undefined) byId.set(p.id, p.name);
      else if (bare(seen) !== bare(p.name)) clashes.push(`${p.id}: ${seen} vs ${p.name}`);
    }
    expect(clashes).toEqual([]);
  });

  it('lands 194 pool players on an id the shipped set already uses', () => {
    // Not a requirement, a canary: this was 177 while accents collapsed to
    // underscores. If it drops, the id scheme has drifted off the convention
    // src/game/rawCards.js and public/cards/players/ were built on.
    const shipped = new Set(CARD_PLAYERS.map(p => p.id));
    expect(POOL_PLAYERS.filter(p => shipped.has(p.id))).toHaveLength(194);
  });
});

describe('SOURCES', () => {
  it('offers the new pool and the shipped card set', () => {
    expect(SOURCES.pool.players).toHaveLength(331);
    expect(SOURCES.cards.players).toHaveLength(306);
  });

  it('sorts both by name so the list order is predictable', () => {
    for (const source of Object.values(SOURCES)) {
      const names = source.players.map(p => p.name);
      expect(names).toEqual([...names].sort((a, b) => a.localeCompare(b)));
    }
  });

  it('gives the shipped set full stats, unlike the pool', () => {
    expect(SOURCES.cards.players[0].chart.length).toBeGreaterThan(0);
  });
});

describe('photoProgress', () => {
  it('counts how many of the active set have a photo', () => {
    expect(photoProgress(SAMPLE, ['Kevin_Durant'])).toEqual({
      withPhoto: 1,
      total: 3,
      missing: 2,
    });
  });

  it('ignores photos belonging to players outside the active set', () => {
    // card-art/photos/ accumulates files from both sources; counting the
    // shipped-card photos against the 331-player pool would inflate progress.
    expect(photoProgress(SAMPLE, ['08_09_LeBron_James', 'Kevin_Durant'])).toMatchObject({
      withPhoto: 1,
      total: 3,
    });
  });

  it('handles an empty set and missing photo data', () => {
    expect(photoProgress([], [])).toEqual({ withPhoto: 0, total: 0, missing: 0 });
    expect(photoProgress(SAMPLE, undefined)).toMatchObject({ withPhoto: 0, missing: 3 });
  });

  it('accepts a Set as well as an array', () => {
    expect(photoProgress(SAMPLE, new Set(['Kevin_Durant'])).withPhoto).toBe(1);
  });
});

describe('filterPlayers', () => {
  it('returns everyone with no filter', () => {
    expect(filterPlayers(SAMPLE, {})).toHaveLength(3);
  });

  it('matches on name, case-insensitively', () => {
    expect(filterPlayers(SAMPLE, { query: 'duran' }).map(p => p.name)).toEqual(['Kevin Durant']);
  });

  it('matches on team and position too', () => {
    expect(filterPlayers(SAMPLE, { query: 'PHI' }).map(p => p.name)).toEqual(['Tyrese Maxey']);
    expect(filterPlayers(SAMPLE, { query: 'pg' })).toHaveLength(2);
  });

  it('matches accented names by their accented spelling', () => {
    expect(filterPlayers(SAMPLE, { query: 'dončić' })).toHaveLength(1);
  });

  it('narrows to players still missing a photo', () => {
    const out = filterPlayers(SAMPLE, { missingOnly: true, photoIds: ['Kevin_Durant'] });
    expect(out.map(p => p.name)).toEqual(['Tyrese Maxey', 'Luka Dončić']);
  });

  it('combines the text filter with missing-only', () => {
    const out = filterPlayers(SAMPLE, {
      query: 'PG',
      missingOnly: true,
      photoIds: ['Tyrese_Maxey'],
    });
    expect(out.map(p => p.name)).toEqual(['Luka Dončić']);
  });
});

describe('stepSelection', () => {
  const ids = SAMPLE.map(p => p.id);

  it('moves down and up the list', () => {
    expect(stepSelection(SAMPLE, ids[0], 1)).toBe(ids[1]);
    expect(stepSelection(SAMPLE, ids[1], -1)).toBe(ids[0]);
  });

  it('clamps at both ends rather than wrapping', () => {
    expect(stepSelection(SAMPLE, ids[0], -1)).toBe(ids[0]);
    expect(stepSelection(SAMPLE, ids[2], 1)).toBe(ids[2]);
  });

  it('resumes from where a filtered-out selection was, not from the top', () => {
    // The workflow this exists for: "needs photo" is on, a photo is dropped on
    // the player at index 1, they leave the list, and the next keypress must
    // land on whoever took their place — not back at row 0.
    expect(stepSelection(SAMPLE, 'Gone_Player', 1, 1)).toBe(ids[1]);
    expect(stepSelection(SAMPLE, 'Gone_Player', -1, 1)).toBe(ids[0]);
  });

  it('clamps a stale anchor to the list it is given', () => {
    expect(stepSelection(SAMPLE, 'Gone_Player', 1, 99)).toBe(ids[2]);
    expect(stepSelection(SAMPLE, 'Gone_Player', -1, 0)).toBe(ids[0]);
  });

  it('falls to the first entry when there is no anchor to resume from', () => {
    expect(stepSelection(SAMPLE, 'Nobody_At_All', 1)).toBe(ids[0]);
  });

  it('returns null for an empty list', () => {
    expect(stepSelection([], 'x', 1)).toBeNull();
    expect(stepSelection([], 'x', 1, 3)).toBeNull();
  });
});
