// SEASON SCHEDULES AND STANDINGS — pure rules, no browser, no Firebase.
//
// See docs/plans/2026-09-07-game-modes-design.md. A season is a round-robin:
// every pair of teams meets `meetings` times, generated by the circle method
// so each round uses every team once (an odd league gets a bye). Home and
// away alternate across meetings so a Regular season is one home and one
// away against everyone.

/** The user's "variable season lengths", as how many times each pair meets. */
export const LENGTHS = {
  short: { id: 'short', label: 'Short', meetings: 1, blurb: 'Everyone once' },
  regular: { id: 'regular', label: 'Regular', meetings: 2, blurb: 'Home and away' },
  long: { id: 'long', label: 'Long', meetings: 3, blurb: 'Everyone three times' },
};
export const LENGTH_IDS = Object.keys(LENGTHS);

/** The league sizes offered. */
export const LEAGUE_SIZES = [4, 6, 8, 10, 12];

/**
 * Round-robin fixtures by the circle method.
 *
 * Returns rounds: each round is a list of `{ home, away }` (team ids), every
 * team appearing once per round; an odd league carries a `null` bye in the
 * rotation and that pairing is dropped. With `meetings` > 1 the whole cycle
 * repeats with home and away swapped on even cycles, so a pair that met
 * home/away in the first cycle meets away/home in the second.
 */
export function roundRobin(teamIds, meetings = 1) {
  const ids = [...teamIds];
  if (ids.length % 2 === 1) ids.push(null);
  const n = ids.length;
  const cycle = [];
  // Circle method: fix ids[0], rotate the rest.
  const rot = ids.slice(1);
  for (let r = 0; r < n - 1; r += 1) {
    const ring = [ids[0], ...rot];
    const round = [];
    for (let i = 0; i < n / 2; i += 1) {
      const a = ring[i];
      const b = ring[n - 1 - i];
      if (a === null || b === null) continue;
      // Alternate which side is home by round so no team is home every time.
      const homeFirst = (r + i) % 2 === 0;
      round.push(homeFirst ? { home: a, away: b } : { home: b, away: a });
    }
    cycle.push(round);
    rot.unshift(rot.pop());
  }
  const rounds = [];
  for (let m = 0; m < meetings; m += 1) {
    for (const round of cycle) {
      rounds.push(m % 2 === 0 ? round.map(f => ({ ...f })) : round.map(f => ({ home: f.away, away: f.home })));
    }
  }
  return rounds;
}

/** Fixtures as flat records with ids, the shape a season stores. */
export function fixturesFrom(rounds) {
  const out = [];
  rounds.forEach((round, r) => {
    round.forEach((f, i) => out.push({ id: `r${r + 1}g${i + 1}`, round: r + 1, home: f.home, away: f.away, result: null }));
  });
  return out;
}

/**
 * Standings from results. A result is `{ home, away, homeScore, awayScore }`.
 * Sorted by wins, then head-to-head wins among the teams tied on wins, then
 * point differential, then points for; `rank` is 1-based.
 */
export function standingsFrom(teamIds, results) {
  const rows = new Map(teamIds.map(id => [id, { id, w: 0, l: 0, pf: 0, pa: 0 }]));
  for (const r of results) {
    if (!r || !rows.has(r.home) || !rows.has(r.away)) continue;
    const h = rows.get(r.home);
    const a = rows.get(r.away);
    h.pf += r.homeScore; h.pa += r.awayScore;
    a.pf += r.awayScore; a.pa += r.homeScore;
    if (r.homeScore > r.awayScore) { h.w += 1; a.l += 1; } else { a.w += 1; h.l += 1; }
  }
  const list = [...rows.values()].map(t => ({ ...t, diff: t.pf - t.pa, gp: t.w + t.l }));
  const h2h = (x, y) => {
    let xw = 0;
    let yw = 0;
    for (const r of results) {
      if (!r) continue;
      const pair = (r.home === x.id && r.away === y.id) || (r.home === y.id && r.away === x.id);
      if (!pair) continue;
      const winner = r.homeScore > r.awayScore ? r.home : r.away;
      if (winner === x.id) xw += 1; else yw += 1;
    }
    return yw - xw;
  };
  list.sort((x, y) => y.w - x.w || h2h(x, y) || y.diff - x.diff || y.pf - x.pf || String(x.id).localeCompare(String(y.id)));
  return list.map((t, i) => ({ ...t, rank: i + 1 }));
}

/** How many teams make the playoffs: half the league, rounded down to a power of two, at least 2. */
export function playoffCount(leagueSize) {
  const half = Math.floor(leagueSize / 2);
  let p = 2;
  while (p * 2 <= half) p *= 2;
  return Math.max(2, p);
}

/** The playoff field, best standing first. */
export function playoffSeeds(standings, count = playoffCount(standings.length)) {
  return standings.slice(0, count).map(t => t.id);
}

/** Games per team for a league of `size` under a length preset. */
export function gamesPerTeam(size, lengthId) {
  return (size - 1) * (LENGTHS[lengthId]?.meetings ?? 1);
}
